TransactionRecordApp/Models/TransactionType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TransactionRecordApp.Models
{
    public class TransactionType
    {
        public string TransactionTypeId { get; set; }
        public string Name { get; set; }
        public double CommissionFee { get; set; }
    }
}

TransactionRecordApp/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

using TransactionRecordApp.Models;

namespace TransactionRecordApp.Controllers
{
    /// <summary>
    /// Controls the Add, Edit and Delete functions
    /// </summary>
    public class TransactionController : Controller
    {
        public TransactionController (TransactionContext transactionConatext)
        {
            _tranactionContext = transactionConatext;
        }

        /// <summary>
        /// Action to allow the user to add a new transaction
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        public IActionResult Add()
        {
            // Set the action to Add
            ViewBag.Action = "Add";

            // Get the transaction types and add them to the Viewbag
            ViewBag.TransactionTypes = _tranactionContext.TransactionType.OrderBy(t => t.Name).ToList();

            // Return the blank Edit form by naming it
            return View("Edit", new Transaction());
        }
        /// <summary>
        /// If there are no errors in the inputs, the transaction is added
        /// If there are errors, the page is returned with the errors
        /// </summary>
        /// <param name="transaction"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult Add(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                _tranactionContext.Transactions.Add(transaction);
                _tranactionContext.SaveChanges();
                return RedirectToAction("Index", "Transactions");
            }
            else
            {
                ViewBag.Action = "Add";
                return View("Edit", transaction);
            }
        }

        /// <summary>
        /// Allows user to edit a movie
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        public IActionResult Edit(int id)
        {
            // Set the action to Edit
            ViewBag.Action = "Edit";

            var transaction = _tranactionContext.Transactions.Find(id);

            // Get the transaction types and add them to the Viewbag
            ViewBag.TransactionTypes = _tranactionContext.TransactionType.OrderBy(t => t.Name).ToList();

            // Return the Edit form
            return View(transaction);
        }
        /// <summary>
        /// If there are no errors in the inputs, the transaction is updated
        /// If there are errors, the page is returned with the errors
        /// </summary>
        /// <param name="transaction"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult Edit(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                // It's valid so we update the transaction
                _tranactionContext.Transactions.Update(transaction);
                _tranactionContext.SaveChanges();
                return RedirectToAction("Index", "Transactions");
            }
            else
            {
                // It's not valid so we return the Transaction
                // to the Edit view by setting the action to Edit again
                ViewBag.Action = "Edit";
                ViewBag.TransactionTypes = _tranactionContext.TransactionType.OrderBy(t => t.Name).ToList();
                return View(transaction);
            }
        }

        /// <summary>
        /// Allows user to delete a movie
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            // Find the trnsaction in the DB and save it to a variable
            var transaction = _tranactionContext.Transactions.Find(id);

            // Return the Delete form
            return View(transaction);
        }
        /// <summary>
        /// Delete the movie
        /// </summary>
        /// <param name="transaction"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Transaction transaction)
        {
            // Delete the movie
            _tranactionContext.Transactions.Remove(transaction);
            _tranactionContext.SaveChanges();
            return RedirectToAction("Index", "Transactions");
        }

        private TransactionContext _tranactionContext;
    }
}

TransactionRecordApp/Controllers/TransactionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

using TransactionRecordApp.Models;

namespace TransactionRecordApp.Controllers
{
    /// <summary>
    /// Contoller of the Transactions Index (main) page
    /// </summary>
    public class TransactionsController : Controller
    {
        public TransactionsController(TransactionContext transactionContext)
        {
            _transactionContext = transactionContext;
        }

        /// <summary>
        /// Calls the Transactions Index (main) page and passes all the transactions to it
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            // make the database into a list ordered by the Company Name
            var transactions = _transactionContext.Transactions.Include(o => o.TransactionType).OrderBy(o => o.CompanyName).ToList();

            // Then pass the list of traansactions to the view
            return View(transactions);
        }

        // Set the private variable
        private TransactionContext _transactionContext;
    }
}

TransactionRecordApp/Views/Transaction/Delete.cshtml
@model Transaction

@{
    ViewData["Title"] = "Delete";
}

<h2>Comfirm Deletion</h2>
<h3>@Model.Quantity shares of @Model.CompanyName (@Model.TickerSymbol) - share price: @Model.SharePrice.ToString("c")</h3>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="TransactionId" />

    <input type="submit" class="btn btn-primary" value="Delete" />
    <a asp-controller="Transactions" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

TransactionRecordApp/Views/Transaction/Edit.cshtml
@model Transaction

@{
    string title = ViewBag.Action + " Transaction";
    ViewData["Title"] = title;
}

<form asp-controller="Transaction" asp-action="@ViewBag.Action" method="post" enctype="application/x-www-form-urlencoded">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="TickerSymbol">Ticker Symbol</label>
        <input type="text" asp-for="TickerSymbol" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="TransactionTypeId">Transaction Type</label>
        <select asp-for="TransactionTypeId" class="form-control">
            <option value="">Select a transaction type...</option>
            @foreach (TransactionType t in ViewBag.TransactionTypes)
            {
                <option value="@t.TransactionTypeId">@t.Name</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label asp-for="CompanyName">Company Name</label>
        <input type="text" asp-for="CompanyName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Quantity">Quantity</label>
        <input type="text" asp-for="Quantity" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="SharePrice">Share Price</label>
        <input type="text" asp-for="SharePrice" class="form-control" />
    </div>

    <input type="hidden" asp-for="TransactionId" />

    <input type="submit" class="btn btn-primary" value="@ViewBag.Action" />
    <a asp-controller="Transactions" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>